Lecture 3/hw
AlexyShu/react-20230914 pull request #3
Opened 2023-10-01 15:03 UTC by AlexyShu

2023-10-02 14:35 UTC, SArchieEdu commented on src/components/Button/component.jsx
> +            className={
лучше использовать classNames,  как на лекциях

2023-10-02 14:35 UTC, SArchieEdu commented on src/components/Footer/styles.module.css
> +    margin-top: auto;
margin это внешний стиль, тк отвечает за позицию относительно дргуих

2023-10-02 14:35 UTC, SArchieEdu commented on src/components/Header/styles.module.css
> +    position: sticky;
это внешний стиль как и марджин, тк отвечает за позицию на странице

2023-10-05 11:46 UTC, SArchieEdu requested changes

2023-10-05 11:46 UTC, SArchieEdu commented on src/index.css
> +}
выносить эти стили во внешние не самая лучшая идея, тк на других страницах нам может потребоваться другие стили, придется перекрывать. Лучше унести эти стили и само использование шапки и футера на страницу

2023-10-05 11:46 UTC, SArchieEdu commented on src/components/MenuItem/styles.module.css
> +    margin-bottom: 10px;
это внешний стиль

2023-10-05 11:46 UTC, SArchieEdu commented on src/components/Dish/component.jsx
> +        <li className={styles.dish}>
элемент li не нужно добавлять в dish, тк его использование ограничивает область применения компонента. Сейчас компонент Dish можно использовать только с ul  в родителе, а это плохо, лишние связи. Лучше обарачивать Dish в li уже в родителе, там где это нужно

2023-10-05 11:46 UTC, SArchieEdu commented on src/components/Dish/styles.module.css
> +    margin-bottom: 10px;
внешний стиль

2023-10-05 11:46 UTC, SArchieEdu commented on src/components/Button/styles.module.css
> +    margin-right: 4px;
внешний стиль

2023-10-07 09:01 UTC, AlexyShu commented on src/components/Button/styles.module.css
> +    margin-right: 4px;
я не понимаю. 
Эти относится конкретно к данному компонту кнопки же.
Куда это надо вынести?
В index.css???

2023-10-07 09:03 UTC, AlexyShu commented on src/components/Dish/styles.module.css
> +    margin-bottom: 10px;
тут тоже не понимаю. Данный стиль относится строго к этому компоненту,
Куда его надо выносить?
В index.css?

2023-10-09 11:13 UTC, SArchieEdu requested changes

2023-10-09 11:13 UTC, SArchieEdu commented on src/pages/Main/styles.module.css
> +header {
это не очень очевидно, тк мы в родительском компоненте не можем точно утверждать, что в хедере есть элемент header, мб там реализация через div. Такой подход заставляет родителя знать о реализации дочернего, это плохо. Лучше просто сделать класс и передать в className хедеру

2023-10-09 11:13 UTC, SArchieEdu commented on src/pages/Main/styles.module.css
> +footer {
аналогично

2023-10-09 11:13 UTC, SArchieEdu commented on src/index.css
> +}
эти стили не нужно описывать в глобальных, тк это стили отдельных элементов, а не всего приложения

2023-10-09 11:13 UTC, SArchieEdu commented on src/index.css
> +}
переместите эти стили в свои компоненты, но только предварительно разделите их на внешние и внутрениие. внутренние в самом компоненте, а внешние в родителе и передавайте через className

2023-10-11 18:36 UTC, merged